# ONE HOT ENCODING

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\us\\OneDrive\\Desktop\\regexml\\covid_toy.csv")

In [4]:
df=df.dropna()

In [5]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [6]:
df=df.drop(columns=['age','fever'])

In [7]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
df.shape

(90, 4)

# get_dummies method()

In [13]:
p=pd.get_dummies(df,columns=['gender','cough','city','has_covid'])

In [14]:
p

gender_Female  gender_Male  cough_Mild  cough_Strong  city_Bangalore  \
0               0            1           1             0               0   
1               0            1           1             0               0   
2               0            1           1             0               0   
3               1            0           1             0               0   
4               1            0           1             0               0   
..            ...          ...         ...           ...             ...   
95              1            0           1             0               1   
96              1            0           0             1               0   
97              1            0           1             0               1   
98              1            0           0             1               0   
99              1            0           0             1               0   

    city_Delhi  city_Kolkata  city_Mumbai  has_covid_No  has_covid_Yes  
0            0             1            0             1              0  
1            1             0            0             0              1  
2            1             0            0             1              0  
3            0             1            0             1              0  
4            0             0            1             1              0  
..         ...           ...          ...           ...            ...  
95           0             0            0             1              0  
96           0             1            0             0              1  
97           0             0            0             1              0  
98           0             0            1             1              0  
99           0             1            0             0              1  

[90 rows x 10 columns]

In [15]:
p=pd.get_dummies(df,columns=['gender','cough','city','has_covid'],drop_first=True)

In [16]:
p

gender_Male  cough_Strong  city_Delhi  city_Kolkata  city_Mumbai  \
0             1             0           0             1            0   
1             1             0           1             0            0   
2             1             0           1             0            0   
3             0             0           0             1            0   
4             0             0           0             0            1   
..          ...           ...         ...           ...          ...   
95            0             0           0             0            0   
96            0             1           0             1            0   
97            0             0           0             0            0   
98            0             1           0             0            1   
99            0             1           0             1            0   

    has_covid_Yes  
0               0  
1               1  
2               0  
3               0  
4               0  
..            ...  
95              0  
96              1  
97              0  
98              0  
99              1  

[90 rows x 6 columns]

In [17]:
p.shape

(90, 6)

In [19]:
ohe=OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [21]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [22]:
df_new.shape

(90, 6)

# COLUMN TRANSFORMER

In [39]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder

In [40]:
df=pd.read_csv("C:\\Users\\us\\OneDrive\\Desktop\\regexml\\covid_toy.csv")

In [41]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [42]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [43]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [44]:
x_train

age  gender  fever   cough       city
98    5  Female   98.0  Strong     Mumbai
78   11    Male  100.0    Mild  Bangalore
65   69  Female  102.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
44   20    Male  102.0  Strong      Delhi
..  ...     ...    ...     ...        ...
87   47    Male  101.0  Strong  Bangalore
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
30   15    Male  101.0    Mild      Delhi
54   60  Female   99.0    Mild     Mumbai

[80 rows x 5 columns]

# MANUALLY TYPE OUTPUT

In [45]:
#ADDING SIMPLE IMPUTER TO FEVER COLUMN
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

#ALSO THE TEST DATA
x_train_fever=si.fit_transform(x_test[['fever']])

In [46]:
x_train_fever.shape

(20, 1)

In [47]:
#ordinary encoding
oe=OrdinaryEncoding(catogries=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

#also test data
x_test_cough=oe.

SyntaxError: invalid syntax (<ipython-input-47-239ee55a1bf0>, line 6)

In [48]:
#ONEHOTENCODING --> GENDER , CITY
ohe=OneHotEncoding(drop='first' , sparse=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

#also the test data
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

NameError: name 'OneHotEncoding' is not defined

In [49]:
x_train_age.shape

NameError: name 'x_train_age' is not defined

In [ ]:
x_train_transfromed=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough , axis=1))

In [ ]:
#x_test_transform=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,))

In [ ]:
x_train_transformed.shape

# by the help of column transformer

In [50]:
from sklearn.compose import ColumnTransformer   #THIS IS HOW TO IMPORT COLUMN TRANSFORMER

transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),  
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')    #REMAINDER=passthrough===>it means rest of all columns remain same

In [52]:
transformer.fit_transform(x_train).shape

(80, 7)

In [53]:
transformer.transform(x_test).shape

(20, 7)

# FUNCTION TRANSFORMER

In [58]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a data  set
x=np.array([[1,2],[3,4]])

#define transformation function
log_transform=FunctionTransformer(np.log1p)

#apply the transformation to the data set
x_transformed=log_transform.transform(x)

#view the transformed dat
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


# TYPE OF FUNCTION TRANSFORMER IN MACHINE LERANING

In [56]:
#EG=2
#CUSTOM FEATURE ENGINEERING
#DEFINE A CUSTOM FEATURE ENGINEERING FUNCTION
def my_feature_engineering(x):
    return np.hstack((x,x**2))

#CREATE A FUNCTION TRANSFORMER TO APPLY THE CUSTOM FUNCTION
custom_transformer=FunctionTransformer(my_feature_engineering)

#apply the transform to the input dat
x_transformed=custom_transformer.transform(x)

#view the transformed data
print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [61]:
#EG=3
def my_Scaling(x):
    return x / np.max(x)

#CREATE A FUNCTION TRANSFORMER TO APPLY THE CUSTOM FUNCTION
custom_transformer=FunctionTransformer(my_Scaling)

#apply the transform to the input dat
x_transformed=custom_transformer.transform(x)

#view the transformed data
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


# (3).DATA CLEANING

In [63]:
#EG=4

x=np.array([[1,2],[3,np.nan]])
def my_cleaning(x):
    x[np.isnan(x)]=0
    return x


#CREATE A FUNCTION TRANSFORMER TO APPLY THE CUSTOM FUNCTION
custom_transformer=FunctionTransformer(my_cleaning)

#apply the transform to the input dat
x_transformed=custom_transformer.transform(x)

#view the transformed data
print(x_transformed)

[[1. 2.]
 [3. 0.]]
