# (4).DIAG==>THIS FUNCTION CREATE A TWO DIMENSIONAL ARRAY WITH ALL THE DIAGONAL ELEMENTS AS A GIVEN VALUE AND REST ARE ZERO

In [1]:
import numpy as np
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# (5).randint==>this function is used to generate a random number between a given range

# syntax=randint(min_value,max_max,total_number)

In [1]:
import numpy as np
a=np.random.randint(1,10,3)
a

array([1, 8, 5])

# (6).rand()==>this function is used to generate a random number between 0 to 1
syntax=rand(number if values)

In [3]:
import numpy as np
a=np.random.rand(3)
a

array([0.01092838, 0.22814178, 0.47433428])

# (7).randn()==>this function is used to generate a random number from -3 to close 3.this may return positive or negative numbers as well

In [4]:
import numpy as np
a=np.random.randn(4)
a

array([-1.49621427, -0.57448044,  0.93414074,  1.04469386])

# RESHAPING DATA

In [5]:
import numpy as np
a=np.random.randint(1,50,12)
a

array([13, 32,  8,  9, 22, 11, 30, 26, 14, 49, 43, 11])

In [6]:
a.shape

(12,)

In [7]:
a=a.reshape(12,1)
a


array([[13],
       [32],
       [ 8],
       [ 9],
       [22],
       [11],
       [30],
       [26],
       [14],
       [49],
       [43],
       [11]])

In [8]:
a=a.reshape(6,2)
a

array([[13, 32],
       [ 8,  9],
       [22, 11],
       [30, 26],
       [14, 49],
       [43, 11]])

In [9]:
a=a.reshape(5,3)
a

ValueError: cannot reshape array of size 12 into shape (5,3)

In [10]:
a=a.reshape(3,4)
a

array([[13, 32,  8,  9],
       [22, 11, 30, 26],
       [14, 49, 43, 11]])

In [12]:
import numpy as np
a=np.random.randint(1,100,64)
a

array([26, 52, 31, 95, 60, 17, 63, 91, 16,  9, 65, 62, 73, 26, 35, 29, 60,
        5, 17, 57, 62, 77, 59, 78, 40, 89, 93, 95, 29, 53, 40, 45, 38, 86,
       34, 70, 16, 69, 48, 44, 42, 62, 66, 74, 78, 66, 34, 10, 12, 74, 96,
        5, 58,  6, 94, 45, 30, 40, 16, 50,  5, 13, 19,  7])

In [13]:
a=a.reshape(1,64)
a

array([[26, 52, 31, 95, 60, 17, 63, 91, 16,  9, 65, 62, 73, 26, 35, 29,
        60,  5, 17, 57, 62, 77, 59, 78, 40, 89, 93, 95, 29, 53, 40, 45,
        38, 86, 34, 70, 16, 69, 48, 44, 42, 62, 66, 74, 78, 66, 34, 10,
        12, 74, 96,  5, 58,  6, 94, 45, 30, 40, 16, 50,  5, 13, 19,  7]])

In [14]:
a=a.reshape(64,1)
a

array([[26],
       [52],
       [31],
       [95],
       [60],
       [17],
       [63],
       [91],
       [16],
       [ 9],
       [65],
       [62],
       [73],
       [26],
       [35],
       [29],
       [60],
       [ 5],
       [17],
       [57],
       [62],
       [77],
       [59],
       [78],
       [40],
       [89],
       [93],
       [95],
       [29],
       [53],
       [40],
       [45],
       [38],
       [86],
       [34],
       [70],
       [16],
       [69],
       [48],
       [44],
       [42],
       [62],
       [66],
       [74],
       [78],
       [66],
       [34],
       [10],
       [12],
       [74],
       [96],
       [ 5],
       [58],
       [ 6],
       [94],
       [45],
       [30],
       [40],
       [16],
       [50],
       [ 5],
       [13],
       [19],
       [ 7]])

In [16]:
a=a.reshape(32,2)
a

array([[26, 52],
       [31, 95],
       [60, 17],
       [63, 91],
       [16,  9],
       [65, 62],
       [73, 26],
       [35, 29],
       [60,  5],
       [17, 57],
       [62, 77],
       [59, 78],
       [40, 89],
       [93, 95],
       [29, 53],
       [40, 45],
       [38, 86],
       [34, 70],
       [16, 69],
       [48, 44],
       [42, 62],
       [66, 74],
       [78, 66],
       [34, 10],
       [12, 74],
       [96,  5],
       [58,  6],
       [94, 45],
       [30, 40],
       [16, 50],
       [ 5, 13],
       [19,  7]])

In [15]:
a=a.reshape(2,32)
a

array([[26, 52, 31, 95, 60, 17, 63, 91, 16,  9, 65, 62, 73, 26, 35, 29,
        60,  5, 17, 57, 62, 77, 59, 78, 40, 89, 93, 95, 29, 53, 40, 45],
       [38, 86, 34, 70, 16, 69, 48, 44, 42, 62, 66, 74, 78, 66, 34, 10,
        12, 74, 96,  5, 58,  6, 94, 45, 30, 40, 16, 50,  5, 13, 19,  7]])

In [17]:
a=a.reshape(8,8)
a

array([[26, 52, 31, 95, 60, 17, 63, 91],
       [16,  9, 65, 62, 73, 26, 35, 29],
       [60,  5, 17, 57, 62, 77, 59, 78],
       [40, 89, 93, 95, 29, 53, 40, 45],
       [38, 86, 34, 70, 16, 69, 48, 44],
       [42, 62, 66, 74, 78, 66, 34, 10],
       [12, 74, 96,  5, 58,  6, 94, 45],
       [30, 40, 16, 50,  5, 13, 19,  7]])

In [19]:
#
a=a.reshape(-1,4)
a

array([[26, 52, 31, 95],
       [60, 17, 63, 91],
       [16,  9, 65, 62],
       [73, 26, 35, 29],
       [60,  5, 17, 57],
       [62, 77, 59, 78],
       [40, 89, 93, 95],
       [29, 53, 40, 45],
       [38, 86, 34, 70],
       [16, 69, 48, 44],
       [42, 62, 66, 74],
       [78, 66, 34, 10],
       [12, 74, 96,  5],
       [58,  6, 94, 45],
       [30, 40, 16, 50],
       [ 5, 13, 19,  7]])

# seed function()==>we know that randint function generates random number. evertime we run the program,new set of random number is genrated . so , solve this problem we will use seed function 

In [21]:
import numpy as np
np.random.seed(5)
a=np.random.randint(1,100,12)
a

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8, 77, 16])

In [24]:
np.random.seed(12)
a=np.random.randint(1,500,100).reshape(50,2)
a

array([[332, 156],
       [391, 254],
       [242, 131],
       [260, 452],
       [333, 433],
       [279,  50],
       [437, 390],
       [142, 474],
       [419, 460],
       [119,  75],
       [385, 374],
       [105, 205],
       [270,  83],
       [ 90, 292],
       [447, 101],
       [420, 418],
       [159, 120],
       [448, 353],
       [147, 471],
       [435, 209],
       [469, 135],
       [124, 110],
       [ 74, 174],
       [415, 241],
       [161, 111],
       [ 28, 188],
       [474, 188],
       [473, 336],
       [ 26, 247],
       [226, 313],
       [261, 481],
       [453,  66],
       [492, 301],
       [422, 204],
       [246, 372],
       [325, 182],
       [204, 310],
       [108, 176],
       [ 61, 481],
       [171, 199],
       [327, 110],
       [452, 131],
       [157, 459],
       [ 59,  60],
       [ 85, 356],
       [378, 183],
       [184, 213],
       [492, 238],
       [482,  21],
       [414, 106]])

# view vs copy==>when we slice a sub array from an array,it may be done by two ways

In [25]:
#view
import numpy as np
a=np.array([10,20,43,65,35,86,23])
b=a[2:6]
b[:]=0
a

array([10, 20,  0,  0,  0,  0, 23])

In [29]:
#copy
import numpy as np
a=np.array([10,20,43,65,35,86,23])
b=a[2:6].copy()
b[:]=0
a

array([10, 20, 43, 65, 35, 86, 23])

In [30]:
b

array([0, 0, 0, 0])

# conditional selection

In [32]:
import numpy as np
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [33]:
a>10


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [34]:
a<15

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False])

In [36]:
b=a>10
a[b]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# OPERATIONS ON ARRAY

In [42]:
import numpy as np
a=np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [43]:
a+2

array([3, 4, 5, 6])

In [44]:
a-2

array([-1,  0,  1,  2])

In [45]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [46]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [47]:
b=np.array([3,6,8,6]).reshape(2,2)
b

array([[3, 6],
       [8, 6]])

In [48]:
a+b

array([[ 4,  8],
       [11, 10]])

In [49]:
b-a


array([[2, 4],
       [5, 2]])

In [50]:
a*b

array([[ 3, 12],
       [24, 24]])

In [51]:
a.dot(b)

array([[19, 18],
       [41, 42]])

# some more important numpy function

In [53]:
import numpy as np
a=np.array([10,20,30,40,50])
np.min(a)

10

In [54]:
np.min(a)

10

In [55]:
np.argmin(a) #arg index value 

0

In [56]:
np.argmax(a)

4

In [58]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [59]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# linspace()==>this function returns value between a given range and with a same gap between consicutive elements

In [60]:
import numpy as np
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# np.unique(arr,return_index=True , return counts=true)

In [61]:
#returns 3 array (1)=the array unique values
#(2).the array with respective index values
#(3).the array with counting of frequency
a=np.array([10,20,30,40,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([1, 1, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [62]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [63]:
b

array([5, 6, 7, 8])

In [64]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])