In [1]:
#INTRODUCTION TO NUMPY
#WHY NUMPY IS BETTER THAN LIST?
#->same data type===>array
#->memory comsume===>numpy less, list high
#->computation power===>numpy high , list less
#->functions===>numpy high , list less

In [2]:
import numpy as np

In [4]:
a=[12,43,53,65]
print(type(a))

<class 'list'>


In [8]:
b=np.array(a)
b

array([12, 43, 53, 65])

In [9]:
type(b)

numpy.ndarray

In [13]:
a=int(input("enter any list="))
b=[]
for i in range(a):
    c=int(input("enter any numer="))
    b.append(c)
d=np.array(b)
d

enter any list=3
enter any numer=23
enter any numer=12
enter any numer=43


array([23, 12, 43])

# how to check size and shape of an array?

In [16]:
#shape=n(row),n(column)
#size=total_elements===>n(row)*n(column)
print("total shape=",d.shape)
print("total elements=",d.size)

total shape= (3,)
total elements= 3


In [2]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print("total sisze",b.size)
print("total shape",b.shape)

total sisze 9
total shape (3, 3)


In [21]:
#image===>pixels===>(0,255)px===>0px(complete black) and 255px(complete white)
#convert==>grayscale image
#image(pixels)==>normalization(0-1)==>0px(black),1px(white)
#0-1 ==>neoren system
#matrix==>rowns and column
#symmetric matrix=no. of rows=no. of column
#asymmetric matrix=row!=column
#diagonal matrix==>(1,1)(2,2)(3,3)........(n,n)


# (1).zeros()===>it will create an array in which all the elements is zero 

In [22]:
a=np.zeros(2)
a

array([0., 0.])

In [28]:
b=np.zeros((2,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
a=np.shape(b)
a

(2, 6)

# (2).ones()===>it will create an array in which all the elements are one

In [30]:
a=np.ones(3)
a

array([1., 1., 1.])

In [33]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.shape(b)

(3, 3)

# (3).eye()==>this function create an array in whichh diagonal position element are 1 and rest of all are 0

In [35]:
a=np.eye(3,4)   #asymmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
a=np.eye(4,4)   #symmetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# LAMBDA FUNCTION

In [1]:
l=lambda x:x+10
l(10)

20

In [2]:
a=lambda x:x**2
a(5)

25

In [34]:
a=lambda x:"even number" if x%2==0 else "odd number"
print(a(49))

odd number


In [56]:
a=[23,75,35,90,67]
a.sort()
a.reverse()
print("Highest number = " , a[0])
print("Second Highest number = " , a[1])

Highest number =  90
Second Highest number =  75


In [44]:
def func(n):
    return lambda x:x+n
a=func(2)
print(a(4))

6


# MAP FUNCTION

In [15]:
a=(10,20,30,40)
b=list(map(lambda x:x+x,a))
b

[20, 40, 60, 80]

In [16]:
def func(x,y):
    return x+y
A=[1,2,3,4]
B=[1,6,4,9]
C=list(map(func,A,B))
C

[2, 8, 7, 13]

In [23]:
a=["cricket","football","basketball"]
b=list(map(lambda x:[i for i in x],a))
b

[['c', 'r', 'i', 'c', 'k', 'e', 't'],
 ['f', 'o', 'o', 't', 'b', 'a', 'l', 'l'],
 ['b', 'a', 's', 'k', 'e', 't', 'b', 'a', 'l', 'l']]

# MATRIX FUNCTION

In [29]:
import numpy as np
a=np.ones((3,3))
b=np.ones((3,3))
a+b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [48]:
a = []
size = int(input("Enter sizie:"))
for i in range(size):
    val = int(input("Enter item:"))
    a.append(val)
b = np.array(a) 
b.resize(2,2)
b

Enter sizie:4
Enter item:1
Enter item:2
Enter item:3
Enter item:4


array([[1, 2],
       [3, 4]])

###### FILTER FUNCTION 

In [36]:
a=[1,5,3,6,8,4]
b=list(filter(lambda x:x%2==0,a))
b

[6, 8, 4]

In [5]:
a=["HeLlo","himanshI2","dolly","MItaLI"]
b=list(filter(lambda x:x.isupper(),''.join(a)))
b

['H', 'L', 'I', 'M', 'I', 'L', 'I']

In [9]:
a=["himanshi","Aadhya",",mitali","italy"]
def func(a):
    return a[0].lower() in ['a', 'e', 'i', 'o', 'u']
b = list(filter(func, a))
print("\nExtract names starting with a vowel:",b)


Extract names starting with a vowel: ['Aadhya', 'italy']


In [ ]:
(4).DIAG==>THIS FUNCTION CREATE A TWO DIMENSIONAL ARRAY WITH ALL THE DIAGONAL